// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "MyActor.generated.h"

/**
 * Example utility actor generated by the template project.
 *
 * Editor Implementation Guide:
 * 1. Derive a Blueprint from AMyActor when you need a lightweight scripted prop or trigger.
 * 2. Add components (StaticMesh, ParticleSystem, etc.) in the Blueprint editor to define visuals and collisions.
 * 3. Override BeginPlay/Tick in Blueprint to drive time-based behavior without modifying the C++ class.
 * 4. Expose BlueprintCallable functions here if the actor must interact with other systems (inventory, skills, etc.).
 * 5. Place Blueprint instances in a level and adjust instance-specific parameters through exposed variables.
 */
UCLASS()
class MO56_API AMyActor : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	AMyActor();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

};
